/** Complete ABI for TrustFlow / OpenImpact contract deployed on Base Sepolia. */
export const openImpactAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "usdcAddress", type: "address", internalType: "address" },
      { name: "initialOwner", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "confirmReceipt",
    inputs: [{ name: "donationId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createDonation",
    inputs: [
      { name: "organisation", type: "address", internalType: "address" },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "donations",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "donor", type: "address", internalType: "address" },
      { name: "organisation", type: "address", internalType: "address" },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "amountUSDC", type: "uint256", internalType: "uint256" },
      { name: "timestamp", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "enum TrustFlow.DonationStatus" },
      { name: "recipientProofHash", type: "string", internalType: "string" },
      { name: "recipientVerification", type: "uint8", internalType: "enum TrustFlow.VerificationStatus" },
      { name: "publicationHash", type: "string", internalType: "string" },
      { name: "publicationVerification", type: "uint8", internalType: "enum TrustFlow.VerificationStatus" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDonation",
    inputs: [{ name: "donationId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct TrustFlow.Donation",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "donor", type: "address", internalType: "address" },
          { name: "organisation", type: "address", internalType: "address" },
          { name: "recipient", type: "address", internalType: "address" },
          { name: "amountUSDC", type: "uint256", internalType: "uint256" },
          { name: "timestamp", type: "uint256", internalType: "uint256" },
          { name: "status", type: "uint8", internalType: "enum TrustFlow.DonationStatus" },
          { name: "recipientProofHash", type: "string", internalType: "string" },
          { name: "recipientVerification", type: "uint8", internalType: "enum TrustFlow.VerificationStatus" },
          { name: "publicationHash", type: "string", internalType: "string" },
          { name: "publicationVerification", type: "uint8", internalType: "enum TrustFlow.VerificationStatus" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextDonationId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitPublication",
    inputs: [
      { name: "donationId", type: "uint256", internalType: "uint256" },
      { name: "publicationHash", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitRecipientProof",
    inputs: [
      { name: "donationId", type: "uint256", internalType: "uint256" },
      { name: "proofHash", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePublicationVerification",
    inputs: [
      { name: "donationId", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "enum TrustFlow.VerificationStatus" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateRecipientVerification",
    inputs: [
      { name: "donationId", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "enum TrustFlow.VerificationStatus" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "usdc",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "DonationCreated",
    inputs: [
      { name: "donationId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "donor", type: "address", indexed: true, internalType: "address" },
      { name: "organisation", type: "address", indexed: true, internalType: "address" },
      { name: "recipient", type: "address", indexed: false, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
      { name: "newOwner", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PublicationSubmitted",
    inputs: [
      { name: "donationId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "publicationHash", type: "string", indexed: false, internalType: "string" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PublicationVerificationUpdated",
    inputs: [
      { name: "donationId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "status", type: "uint8", indexed: false, internalType: "enum TrustFlow.VerificationStatus" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecipientConfirmed",
    inputs: [{ name: "donationId", type: "uint256", indexed: true, internalType: "uint256" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecipientProofSubmitted",
    inputs: [
      { name: "donationId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "proofHash", type: "string", indexed: false, internalType: "string" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecipientVerificationUpdated",
    inputs: [
      { name: "donationId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "status", type: "uint8", indexed: false, internalType: "enum TrustFlow.VerificationStatus" },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC20InsufficientAllowance",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "allowance", type: "uint256", internalType: "uint256" },
      { name: "needed", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ERC20InsufficientBalance",
    inputs: [
      { name: "sender", type: "address", internalType: "address" },
      { name: "balance", type: "uint256", internalType: "uint256" },
      { name: "needed", type: "uint256", internalType: "uint256" },
    ],
  },
] as const;
